language: go

go:
    - 1.8

install:
    - go get gopkg.in/gin-gonic/gin.v1
    - go get github.com/getsentry/raven-go
    - go get github.com/go-sql-driver/mysql
    - go get gopkg.in/guregu/null.v3
