language: go

go:
  - 1.8
  - master

install:
  - go get github.com/gin-gonic/gin
  - go get github.com/getsentry/raven-go
  - go get github.com/go-sql-driver/mysql
  - go get github.com/gin-contrib/cors
